baseURL = 'https://square.concrnt.net'
languageCode = "ja"
title = "Concrnt Square"
theme = "relearn"
hasCJKLanguage = true

[params]
themevariant = [ "blue", "zen-dark" ]
favicon = "https://s3.gammalab.net/icons/Concrnt.png"
description = "Concrnt Squareは分散型SNS「Concrnt(コンカレント)」の始め方からサーバー運用方法、開発ノウハウまで、様々な情報を集約しているサイトです。"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses=false
linenos=true
lineNumbersInTable = true

